### PR TITLE
[MRG]: Add rdf serialization

### PR DESCRIPTION
**Pull request by satra**
This is ready for merge!

### CODE REVIEW

**Comment by satra** [comment]
a few more things to finalize:
- [ ] support bundles (via trig)
- [ ] make the tests run on travis
- [ ] check py3 support
- [ ] settle an issue with Decimal representation
- [ ] skip scruffy round trip tests for now - just ensure they can be read without error for the moment.

**Comment by satra** [comment]
these tests fail round trip - need to figure out a way to skip.

```
FAIL: test_scruffy_end_2 (prov.tests.test_rdf.RoundTripRDFTests)
FAIL: test_scruffy_end_3 (prov.tests.test_rdf.RoundTripRDFTests)
FAIL: test_scruffy_end_4 (prov.tests.test_rdf.RoundTripRDFTests)
FAIL: test_scruffy_generation_2 (prov.tests.test_rdf.RoundTripRDFTests)
FAIL: test_scruffy_invalidation_2 (prov.tests.test_rdf.RoundTripRDFTests)
FAIL: test_scruffy_start_2 (prov.tests.test_rdf.RoundTripRDFTests)
FAIL: test_scruffy_start_3 (prov.tests.test_rdf.RoundTripRDFTests)
FAIL: test_scruffy_start_4 (prov.tests.test_rdf.RoundTripRDFTests)
FAIL: test_scruffy_usage_2 (prov.tests.test_rdf.RoundTripRDFTests)
```

**Comment by satra** [comment]
@trungdong - some of the issues here are unfortunately due to rdflib interactions. but this is good for review. i still need to figure out the python 3 errors, again an interaction with rdflib! and how to suppress the failing scruff tests.

**Comment by satra** [comment]
@trungdong - finally got some time to fix and this is ready for merge :)

**Comment by satra** [comment]
closes #1

**Comment by trungdong** [comment]
Excellent! Thank you very much @satra!!!
I'll try to get some time this week to clean up the current master branch and will make a new release with RDF support soon.

**Pull request merged**
